/* Executed on GitHub-hosted runners only. Production keys are never generated by the build assistant. */
import {randomBytes} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {
  REPOSITORY, MAX_FILE_BYTES, signingKey, publicBytes, keyId, normalizeDevice,
  emptyDatabase, validateDatabase, applyOperation, createEnvelope, verifyEnvelope,
} from './license-core.mjs';

const root = process.cwd();
const secretName = 'SKYFE_SIGNING_SEED';
const files = ['allowed-devices.json', 'public_key.txt', 'published/devices.signed.json', 'published/client_config.json'];
const actionMap = new Map([
  ['Ilk kurulum', 'initialize'], ['Cihaz ekle', 'add'], ['Cihaz kaldir', 'remove'], ['Listeyi yenile', 'renew'],
]);
function stop(code) { throw new Error(code); }
function readText(relative) {
  const filename = path.join(root, relative);
  if (!fs.existsSync(filename)) return null;
  const st = fs.lstatSync(filename);
  if (st.isSymbolicLink() || !st.isFile() || st.size > MAX_FILE_BYTES) stop('UNSAFE_OR_OVERSIZED_FILE');
  return fs.readFileSync(filename, 'utf8');
}
function readJson(relative) {
  const text = readText(relative);
  if (text === null) return null;
  try { return JSON.parse(text); } catch { stop('JSON_FILE_INVALID'); }
}
function atomicText(relative, text) {
  const filename = path.join(root, relative);
  fs.mkdirSync(path.dirname(filename), {recursive: true});
  const tmp = filename + '.tmp';
  fs.writeFileSync(tmp, text, {encoding: 'utf8', flag: 'wx', mode: 0o600});
  fs.renameSync(tmp, filename);
}
function publicJson(relative, value) { atomicText(relative, JSON.stringify(value, null, 2) + '\n'); }
function mask(value) {
  // These seeds contain only hexadecimal characters, so workflow-command escaping is not needed.
  process.stdout.write(`::add-mask::${value}\n`);
}
function cleanEnvironment(extra = {}) {
  const env = {...process.env, ...extra};
  delete env.SKYFE_SIGNING_SEED;
  delete env.SKYFE_SETUP_TOKEN;
  return env;
}
function run(cmd, args, options = {}) {
  const res = spawnSync(cmd, args, {
    cwd: root, timeout: 60000, maxBuffer: 1024 * 1024, encoding: 'utf8',
    env: cleanEnvironment(), ...options,
  });
  if (res.error || res.status !== 0) stop(options.failureCode || 'RUNNER_COMMAND_FAILED');
  return (res.stdout || '').trim();
}
async function hasRemoteSeed(setupToken) {
  let response;
  try {
    response = await fetch(`https://api.github.com/repos/${REPOSITORY}/actions/secrets/${secretName}`, {
      method: 'GET', redirect: 'error', signal: AbortSignal.timeout(20000),
      headers: {
        Accept: 'application/vnd.github+json', Authorization: `Bearer ${setupToken}`,
        'User-Agent': 'Skyfe-License-Setup', 'X-GitHub-Api-Version': '2022-11-28',
      },
    });
  } catch { stop('SETUP_API_UNREACHABLE'); }
  // This response contains metadata only, never the stored value.
  if (response.status === 200) return true;
  if (response.status === 404) return false;
  stop(response.status === 401 ? 'SETUP_TOKEN_INVALID' : 'SETUP_TOKEN_PERMISSION_OR_API_ERROR');
}
async function seedForRun(operation) {
  const provided = (process.env.SKYFE_SIGNING_SEED || '').trim();
  if (provided) { signingKey(provided); mask(provided); return provided; }
  if (operation !== 'initialize') stop('SIGNING_SECRET_MISSING_RUN_INITIALIZE');
  if (readText('public_key.txt') || readText('published/devices.signed.json')) {
    stop('KEY_RECOVERY_REQUIRED_PUBLIC_STATE_EXISTS');
  }
  const setupToken = (process.env.SKYFE_SETUP_TOKEN || '').trim();
  if (!setupToken) stop('SETUP_TOKEN_MISSING');
  if (await hasRemoteSeed(setupToken)) stop('SIGNING_SECRET_EXISTS_RERUN_WORKFLOW');
  const seed = randomBytes(32).toString('hex');
  mask(seed);
  // gh performs Libsodium encryption and sends only the encrypted value to the secrets API.
  // Input comes through stdin, NOT command-line args, output, commit, artifact or summary.
  run('gh', ['secret', 'set', secretName, '--repo', REPOSITORY, '--app', 'actions'], {
    input: seed, env: cleanEnvironment({GH_TOKEN: setupToken}), failureCode: 'SIGNING_SECRET_SAVE_FAILED',
  });
  console.log('Signing secret stored. Its value is not printed or committed.');
  return seed;
}
function assertEnvironment() {
  const branch = process.env.SKYFE_DEFAULT_BRANCH || '';
  if (process.env.GITHUB_ACTIONS !== 'true' || process.env.GITHUB_REPOSITORY !== REPOSITORY) stop('WRONG_REPOSITORY_OR_RUNNER');
  if (!branch || process.env.GITHUB_REF !== `refs/heads/${branch}`) stop('DEFAULT_BRANCH_REQUIRED');
  if (!['workflow_dispatch', 'schedule'].includes(process.env.GITHUB_EVENT_NAME)) stop('EVENT_NOT_ALLOWED');
  if (Number(process.versions.node.split('.')[0]) < 18) stop('NODE_18_REQUIRED');
  run('git', ['check-ref-format', '--branch', branch], {failureCode: 'INVALID_BRANCH'});
  return branch;
}
function writeSummary(lines) {
  const summary = process.env.GITHUB_STEP_SUMMARY;
  if (summary) fs.appendFileSync(summary, lines.join('\n') + '\n', 'utf8');
}
async function main() {
  const branch = assertEnvironment();
  const operation = actionMap.get(process.env.SKYFE_ACTION || '');
  if (!operation) stop('INVALID_OPERATION');
  const input = process.env.SKYFE_DEVICE_CODE || '';
  if (['add', 'remove'].includes(operation)) normalizeDevice(input);

  // The checkout step uses the default branch. Abort rather than force-push if another
  // commit lands during the operation; the owner can rerun against the latest state.
  const startCommit = run('git', ['rev-parse', 'HEAD']);
  const seed = await seedForRun(operation);
  const pub = publicBytes(signingKey(seed)).toString('base64url');
  const currentPub = readText('public_key.txt');
  if (currentPub !== null && currentPub.trim() !== pub) stop('SIGNING_KEY_MISMATCH_NO_ROTATION');

  const oldSigned = readJson('published/devices.signed.json');
  const previous = oldSigned ? verifyEnvelope(oldSigned, pub) : null;
  let db = readJson('allowed-devices.json');
  if (db === null) {
    // Do not erase approved devices just because the human-readable copy was deleted.
    db = previous
      ? {schema: 1, revision: previous.revision, min_app_version: previous.min_app_version, devices: previous.devices}
      : emptyDatabase();
  }
  db = validateDatabase(db);
  const applied = applyOperation(db, operation, input);
  db = applied.database;
  db.revision = Math.max(db.revision, previous?.revision || 0) + 1;
  if (!Number.isSafeInteger(db.revision)) stop('REVISION_OVERFLOW');
  const now = Math.floor(Date.now() / 1000);
  const signed = createEnvelope(db, seed, now);
  const verified = verifyEnvelope(signed, pub, {now});
  const urlBranch = branch.split('/').map(encodeURIComponent).join('/');
  const manifestUrl = `https://raw.githubusercontent.com/${REPOSITORY}/${urlBranch}/published/devices.signed.json`;
  const config = {
    schema: 1, product: 'skyfe-boss-timer', repository: REPOSITORY, branch,
    manifest_url: manifestUrl, public_key: pub, key_id: keyId(Buffer.from(pub, 'base64url')),
    signature_domain: 'SKYFE-DEVICE-LIST-V1\n', min_app_version: db.min_app_version,
    pending_poll_seconds: 30, active_poll_seconds: 300,
  };
  publicJson('allowed-devices.json', db);
  atomicText('public_key.txt', pub + '\n');
  publicJson('published/devices.signed.json', signed);
  publicJson('published/client_config.json', config);

  // Only PUBLIC files above can be added. Never `git add .` in a secret-bearing job.
  run('git', ['config', 'user.name', 'github-actions[bot]']);
  run('git', ['config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com']);
  run('git', ['add', '--', ...files]);
  run('git', ['commit', '-m', `license: ${operation}, revision ${db.revision}`], {failureCode: 'PUBLIC_COMMIT_FAILED'});
  try {
    run('git', ['push', 'origin', `HEAD:refs/heads/${branch}`], {failureCode: 'PUBLIC_PUSH_FAILED_CHECK_PERMISSION_OR_NEW_COMMIT'});
  } catch (error) {
    writeSummary([
      '## Publication failed',
      'The signing secret may already have been created. Do NOT delete it or generate a new key.',
      'Check branch permissions and rerun the same workflow. Nothing is force-pushed.',
    ]);
    throw error;
  }
  writeSummary([
    '# Skyfe license operation completed', '',
    `- Operation: **${operation}**`,
    `- Authorized devices: **${db.devices.length}**`,
    `- Revision: **${db.revision}**`,
    `- Public key fingerprint: \`${config.key_id}\``,
    `- Manifest valid until: **${new Date(verified.valid_until * 1000).toISOString()}**`,
    `- Device list changed: **${applied.changed ? 'yes' : 'no (refresh only)'}**`,
    `- Source commit: \`${startCommit}\``, '',
    `[Public client configuration](https://github.com/${REPOSITORY}/blob/${urlBranch}/published/client_config.json)`,
    `[Published signed list](${manifestUrl})`, '',
    operation === 'initialize'
      ? '**Setup complete. Delete/revoke the temporary setup token; keep SKYFE_SIGNING_SEED.**'
      : 'The EXE may need a short time to see the new version because of HTTP caching.',
    '', 'No private key, setup token, Windows hardware serial or customer name has been published.',
  ]);
  console.log(`Published revision ${db.revision}; devices=${db.devices.length}; operation=${operation}.`);
}
main().catch(error => {
  // Controlled error codes only; never print secret-bearing API responses or child-process objects.
  const code = (error instanceof Error && /^[A-Z0-9_]+$/.test(error.message)) ? error.message : 'UNEXPECTED_ERROR';
  console.error(`Skyfe operation stopped: ${code}`);
  writeSummary(['## Operation stopped', `Error code: \`${code}\``, 'Do not paste secrets into an issue or chat. See README_TR.md.']);
  process.exitCode = 1;
});
